# Generated by Django 5.0.1 on 2024-02-22 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RioLujan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado_de_aprobacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ultima modificacion'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='lote',
            field=models.CharField(max_length=99, null=True, verbose_name='Lote - Parcela'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='margen',
            field=models.CharField(max_length=10, null=True, verbose_name='Margen'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='propietario',
            field=models.CharField(max_length=99, null=True, verbose_name='Propietario'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='usuario',
            field=models.CharField(max_length=99, null=True, verbose_name='Ultima modificacion'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='volfirme',
            field=models.FloatField(default=0.0, null=True, verbose_name='Volumen Firme (m3)'),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='horometro',
            field=models.FloatField(default=0.0, null=True, verbose_name='Horometro'),
        ),
        migrations.AlterField(
            model_name='maquinaria',
            name='nombre',
            field=models.CharField(max_length=99, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='recinto',
            name='capacidad',
            field=models.FloatField(default=0.0, null=True, verbose_name='Volumen Firme (m3)'),
        ),
        migrations.AlterField(
            model_name='recinto',
            name='lote',
            field=models.CharField(max_length=99, null=True, verbose_name='Lote - Parcela'),
        ),
        migrations.AlterField(
            model_name='recinto',
            name='margen',
            field=models.CharField(max_length=10, null=True, verbose_name='Margen'),
        ),
        migrations.AlterField(
            model_name='recinto',
            name='nombre',
            field=models.CharField(max_length=99, null=True, verbose_name='Ultima modificacion'),
        ),
        migrations.AlterField(
            model_name='recinto',
            name='usuario',
            field=models.CharField(max_length=99, null=True, verbose_name='Ultima modificacion'),
        ),
    ]
